# Generated by Django 6.0.4 on 2026-04-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='nom_client',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
